### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by LowlandwasTaken** [anastazialol/Discord-Bot-Website#1]
Hello i cant seem to find a way to contact u!

**Comment by anastazialol** [comment]
Hello, why would you like to contact me?

**Comment by LowlandwasTaken** [comment]
I have some problem regarding that site. I saw ur discord but ur messages are locked so i contacted u here!

**Comment by LowlandwasTaken** [comment]
U may look into my [website](https://whispervc.xyz/) it has some slight problems.

**Comment by anastazialol** [comment]
Will look into it, thank you.

**Comment by anastazialol** [comment]
Hello if the issue was with the images and the buttons the problem is now fixed. Will publish the new changes within 10 minutes.

**Comment by LowlandwasTaken** [comment]
IDK if im dumb but the image is still not fixed.
