### ISSUE TITLE
Image Bug still existing

### ISSUE THREAD

**Issue by LowlandwasTaken** [anastazialol/Discord-Bot-Website#3]
IDK if i did anything wrong but the image bug is still there for me

**Comment by anastazialol** [comment]
Please show me the screenshot on PC

**Comment by LowlandwasTaken** [comment]
Normal aspect Ratio
![image](https://user-images.githubusercontent.com/100024843/222189958-e656039d-289a-4003-b38f-c659adeffa58.png)

16:10 Ratio
<img width="1440" alt="Bildschirm_foto 2023-03-01 um 16 48 10" src="https://user-images.githubusercontent.com/100024843/222190891-3d4f5a97-c51c-4ee1-b0e3-0d4d4a26e4e3.png">

**Comment by LowlandwasTaken** [comment]
Resolution on PC is 1920x1080 (FHD)

On Mac: 3072 x 1920 (4k)

**Comment by anastazialol** [comment]
It makes a lot of more sense now. I haven't yet added a good responsive system to 4k resolutions yet. You can always change it in the ./home.css code! Let me know if there's anything else I can help you with.
